#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

# first arg = mass inlist
function run_mass {

	cp inlists/$1 inlistx_mass
	check_okay
	echo '!--' >> README.md
	echo '!------------- STARTING ' $1 ' -------------!' >> README.md
	echo '!--' >> README.md
	./rnCB
	rm LOGS*/controls{2..100}.data -f
	mkdir $1 # move files to mass specific folder
	mv LOGS* photos* png* *.mod $1/.
}

echo '!-------------------------!' >> README.md
echo '!--- running ./rnMass' >> README.md
echo '!-------------------------!' >> README.md




run_mass x_mass3
run_mass x_mass4





----- ZIP FOR DOWNLOAD
zip -r x_mass.zip x_mass*/LOGS* -x x_mass*/LOGS*/pgstar.dat
echo '!--' >> README.md
echo '!------------- ZIPPED x_mass.zip -------------!' >> README.md
echo '!--' >> README.md


echo '!-------------------------!' >> README.md
echo '!--- finished running ./rnMass' >> README.md
echo '!-------------------------!' >> README.md
