#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1 >> rnMsun.txt
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo >> rnMsun.txt
  	echo "******************************************************************" >> rnMsun.txt
  	echo 'failed to create' $2 'when running' $1 >> rnMsun.txt
  	echo "******************************************************************" >> rnMsun.txt
  	echo >> rnMsun.txt
  	exit 1
  fi
  echo >> rnMsun.txt
  echo 'finished' $1 >> rnMsun.txt
  echo >> rnMsun.txt
	echo '***' >> rnMsun.txt
	echo '***' >> rnMsun.txt
	echo '***' >> rnMsun.txt
	echo '***' >> rnMsun.txt
	echo '***' >> rnMsun.txt
	echo '***' >> rnMsun.txt
	echo >> rnMsun.txt
}

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnMsun.txt
do_one inlist_mSUNc1 mSUNc1.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnMsun.txt
do_one inlist_mSUNc2 mSUNc2.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnMsun.txt
do_one inlist_mSUNc3 mSUNc3.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnMsun.txt

echo 'finished to analyze WIMP interaction'
