#!/bin/bash

echo '!-------------------------!' >> README.md
echo '!--- running ./rnSpin' >> README.md
echo '!-------------------------!' >> README.md

./rnCB
rm LOGS*/controls{2..100}.data -f
#----- ZIP FOR DOWNLOAD
zip -r spinInd.zip LOGS* -x LOGS*/pgstar.dat
echo '!--' >> README.md
echo '!------------- ZIPPED spinInd.zip -------------!' >> README.md
echo '!--' >> README.md
