#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1 >> rnVLM.txt
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo >> rnVLM.txt
  	echo "******************************************************************" >> rnVLM.txt
  	echo 'failed to create' $2 'when running' $1 >> rnVLM.txt
  	echo "******************************************************************" >> rnVLM.txt
  	echo >> rnVLM.txt
  	exit 1
  fi
  echo >> rnVLM.txt
  echo 'finished' $1 >> rnVLM.txt
  echo >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo >> rnVLM.txt
}

#date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
echo date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S" >> rnVLM.txt

do_one inlist_VLM_m08c2 m08c2.mod
echo date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S" >> rnVLM.txt
do_one inlist_VLM_m08c1 m08c1.mod

echo date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S" >> rnVLM.txt
#date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished to analyze WIMP interaction'
