#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1 >> rnVLM.txt
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo >> rnVLM.txt
  	echo "******************************************************************" >> rnVLM.txt
  	echo 'failed to create' $2 'when running' $1 >> rnVLM.txt
  	echo "******************************************************************" >> rnVLM.txt
  	echo >> rnVLM.txt
  	exit 1
  fi
  echo >> rnVLM.txt
  echo 'finished' $1 >> rnVLM.txt
  echo >> rnVLM.txt
	echo '***' >> rnVLM.txt
	echo >> rnVLM.txt
}

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnVLM.txt
do_one inlist_VLM_m1deac m1deac.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnVLM.txt
do_one inlist_VLM_m1c1 m1c1.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnVLM.txt
do_one inlist_VLM_m1c2 m1c2.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnVLM.txt
do_one inlist_VLM_m1c3 m1c3.mod

NOW=$(date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S")
echo $NOW >> rnVLM.txt

echo 'finished to analyze WIMP interaction'
