#!/usr/local/bin/bash
#!/bin/bash


declare -A svals=( [SD]=.TRUE. [SI]=.FALSE.)
declare -A cbvals=( [c0]=0.D0 [c1]=1.D1 [c2]=1.D2 )
declare -A mvals=( [m0p5]=0.5D0 [m1p0]=1.D0 [m1p5]=1.5D0 )



for spin in ${!svals[@]}; do
    mkdir ${spin}
    for cdir in ${!cbvals[@]}; do
        mkdir ${spin}/${cdir}
        for mass in ${!mvals[@]}; do
            mkdir ${spin}/${cdir}/${mass}
                cp xinlist_template ./${spin}/${cdir}/${mass}/inlist_cluster
                cd ${spin}/${cdir}/${mass}
                sed -i 's/s_c_m_/'${spin}${cdir}${mass}'/g; s/cboost_/'${cbvals[${cdir}]}'/g; s/imass_/'${mvals[${mass}]}'/g; s/SD_/'${svals[${spin}]}'/g' inlist_cluster
                cd ..
                cd ..
                cd ..
        done
    done
done
