#!/usr/local/bin/bash


imdir="rnIsoMasses"
mkdir $imdir

# Generate rn files from rnIsoMass_template with subset of mass values (mvals)
#
for n in {1..9}; do
    fname="$imdir/rnIsoMass$n.sh"
    cp rnIsoMass_template.sh $fname
    #masses=$(echo "5.0-0.1*$n 4.0-0.1*$n 3.0-0.1*$n 2.0-0.1*$n" | bc)
    #echo $masses
    #sed -ie 's/mvals=(  )/mvals=( $masses )/g' $fname
done

# extra mass range
fname="$imdir/rnIsoMass0.sh"
cp rnIsoMass_template.sh $fname
sed -ie 's/mvals=(  )/mvals=( 0.9, 0.8 )/g' $fname

#
#

# Generate and run condor_submit script for each rn file
for n in {0..9}; do
    sname="$imdir/isoc$n.submit"
    cp isoc.submit $sname
    fname="$imdir/rnIsoMass$n.sh"
    sed -ie 's runfile.sh '$fname' g; s isoc isoc'$n' g' $sname

    #    condor_submit $sname
done
